//go:build !dynamic && windows && amd64

// THIS FILE IS AUTO-GENERATED BY import.sh; DO NOT EDIT.

package cre2

//#cgo CFLAGS: -I${SRCDIR}/include/. -DUSE_VENDORED_LIBRE2 -O3
//#cgo LDFLAGS: ${SRCDIR}/lib/libre2_linux_amd64.a -lstdc++ -lpthread -O3
import "C"
import "log"

func init() {
	log.Println("[cre2-go] load static windows_amd64")
}
