//go:build !dynamic && linux && 386

// THIS FILE IS AUTO-GENERATED BY import.sh; DO NOT EDIT.

package cre2

//#cgo CFLAGS: -I${SRCDIR}/include/. -O3
//#cgo LDFLAGS: ${SRCDIR}/lib/libre2_linux_amd64.a -lre2 -lstdc++ -lpthread -O3
import "C"
import "log"

func init() {
	log.Println("[cre2-go] load static linux_386")
}
