#!/bin/bash

linux=("386" "amd64" "arm" "arm64")
darwin=("amd64" "arm64")
windows=("386" "amd64" "arm" "arm64")

# static
for os in linux darwin windows; do
    for arch in $(eval echo "$"{$os"[@]"}); do
        echo "Building for build_"$os"_"$arch".go"
        cat >"build_"$os"_"$arch".go" <<EOF
//go:build !dynamic && ${os} && ${arch}

// THIS FILE IS AUTO-GENERATED BY import.sh; DO NOT EDIT.

package cre2

//#cgo CFLAGS: -I\${SRCDIR}/include/. -O3
//#cgo LDFLAGS: \${SRCDIR}/lib/libre2_linux_amd64.a -lre2 -lstdc++ -lpthread -O3
import "C"
import "log"

func init() {
	log.Println("[cre2-go] load static ${os}_${arch}")
}
EOF
    done
done

# dynamic
cat >"build_dynamic.go" <<EOF
//go:build dynamic

package cre2

//#cgo pkg-config: re2
import "C"
import "log"

func init() {
	log.Println("[cre2-go] load dynamic")
}
EOF